# Numpy

In [2]:
# Creating an array

import numpy as np

array = np.array([1,2,3,4])

print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# Using arithmetic operations in an array

import numpy as np

array = np.array([1,2,3,4]) * 2
print(array)
array = np.array([1,2,3,4]) + 2
print(array)
array = np.array([1,2,3,4]) - 2
print(array)


[2 4 6 8]
[3 4 5 6]
[-1  0  1  2]


# Multidimensional Array

In [10]:
import numpy as np

# This is an zero Dimensional array
array = np.array('A')

#ndim function is used to check the dimension of the array
print(array.ndim)

# This is an 1-D array
array = np.array(['A', 'B', 'C'])
print(array.ndim)

0
1


In [11]:
# Creating 2-D array
import numpy as np

array = np.array([['A', 'B', 'C'], 
                  ['D', 'E', 'F'], 
                  ['G', 'H', 'I']])

print(array.ndim)

2


In [25]:
# Creating an 3-D array
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z']]])

# the data is inconsistent and is inhomogenous
# because it is missing an element in the last 


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

In [27]:
import numpy as np
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '1']]])

print(array.ndim)

# shape = to know the shape of an array
print(array.shape)
#Output: (3, 3, 3)
# (Layer, no. of rows, no. of columns)

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]])

print(array.shape)

3
(3, 3, 3)
(2, 3, 3)


In [29]:
# Accessing elements/data in an array

import numpy as np
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '1']]])

# first element of row of first layer
print(array[0, 0, 0])
print(array[0, 0, 1])
print(array[0, 0, 2])

# elements of the first layer second row
print(array[0, 1, 0])
print(array[0, 1, 1])

#elements of the 3rd layer and second row
print(array[2, 1, 2])

A
B
C
D
E
X


In [31]:
# Adding elements together
import numpy as np
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '1']]])

word = array[0, 0, 2] + array[0, 0, 0] + array[2, 0, 1]
print(word)

CAT


# Slicing

In [1]:
import numpy as np

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:stop]

print(array[0]) #return the first row
print(array[2]) # returns the third row

[1 2 3 4]
[ 9 10 11 12]


In [3]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# prints rows from first to 3nd row
print(array[0:3])

print( )
# prints rows from second to 4th row
print(array[1:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
import numpy as np
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[1:4:2])
print( )
print(array[::2])
print( )
print(array[::-2])

[[ 5  6  7  8]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[13 14 15 16]
 [ 5  6  7  8]]


In [10]:
#coloumn selection

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

#array[row, coumn]

# print(array[, 1]) Output will be an error as the row needs a value inside it

print(array[:, 0])
print(array[:, -1])
print(array[:, 2])

[ 1  5  9 13]
[ 4  8 12 16]
[ 3  7 11 15]


In [2]:
import numpy as np
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

# array[start:end:stop]
print(array[:, 1:4])

print(array[:, ::1])

print(array[:, ::-1])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [4]:
print(array[0:2, 0:2])
print(array[0:2, 2:])

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [6]:
print(array[2:, 0:2])
print(array[2:, 2:])

[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


Arithmetic

In [ ]:
import numpy as np

#Scalar arithmetic operations in an array
array = np.array([1,2,3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 2)
print(array ** 4)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.5 1.  1.5]
[ 1 16 81]


In [10]:
# vectorized operations in an array

array1 = np.array([1,2,3])

print(np.sqrt(array1))
print(np.round(array1))
print(np.pi)

[1.         1.41421356 1.73205081]
[1 2 3]
3.141592653589793


In [12]:
# Exercise
radii= np.array([1, 2, 3])

print(np.pi * radii ** 2)


[ 3.14159265 12.56637061 28.27433388]


In [11]:
# Element-wise operations in an array

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [15]:
# Comparison operations in an array

scores = np.array([85, 90, 100, 92, 54])

print(scores == 100)
print(scores >= 60)

scores[scores < 60] = 0
print(scores)

[False False  True False False]
[ True  True  True  True False]
[ 85  90 100  92   0]


# Broadcasting

In [ ]:
# Broadcasting allows Numpy to perform operations on arrays 
# with different shapes by virtually expanding the dimensions
# so they match the larger array's share.

# The dimensions have the same size.
# OR
# one of the dimensions has size of 1.




In [17]:
import numpy as np

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2 )

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:

array1 = np.array([[1,2,3,4],
                   [5,6,7,8]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)
print(array1 * array2 )

# either the number of rows or columns should be the same 
# or one of them should be 1 for broadcasting to work.

# here the number of rows do not match and neither of them is 1, so it will not work.


(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [20]:
import numpy as np

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1.shape)
print(array2.shape)


(1, 10)
(10, 1)


In [21]:

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1 * array2 )

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate Functions

In [ ]:
# Aggregate functions = summarize data and typically 
#                       return a single value

In [22]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array)) # returns the standard deviation of the array
print(np.min(array))
print(np.max(array)) #returns the maximum value in the array
print(np.argmin(array)) # returns the index of the minimum value
print(np.argmax(array)) # returns the index of the maximum value
print(np.var(array)) # returns the variance of the array



55
5.5
2.8722813232690143
1
10
0
9
8.25


In [25]:

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array, axis=0)) # sum of each column


[ 7  9 11 13 15]


In [26]:

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array, axis=1)) # sum of each row   

[15 40]


# Filtering

In [32]:
# Filtering = Refers to the process of selecting specific elements
#             from an array that match a given condition.

import numpy as np

ages = np.array([[25, 15, 35, 54, 60, 12, 70, 11, 80, 85],
                 [22, 14, 13, 50, 55, 62, 68, 72, 12, 16]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18 ) & (ages < 65)] # adults are those whose age is greater than or equal to 18 and less than 65
seniors = ages[ages >= 65] # seniors are those whose age is greater than or equal to 65
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
print(teenagers)
print(adults)
print(seniors)
print(evens) 
print(odds)

[15 12 11 14 13 12 16]
[25 35 54 60 22 50 55 62]
[70 80 85 68 72]
[54 60 12 70 80 22 14 50 62 68 72 12 16]
[25 15 35 11 85 13 55]


In [ ]:

import numpy as np

ages = np.array([[25, 15, 35, 54, 60, 12, 70, 11, 80, 85],
                 [22, 14, 13, 50, 55, 62, 68, 72, 12, 16]])

adults = np.where(ages >= 18, ages, 0) # if the condition is true, it returns the age, otherwise it returns 0
print(adults)



[[25  0 35 54 60  0 70  0 80 85]
 [22  0  0 50 55 62 68 72  0  0]]


# Random Numbers

In [40]:
import numpy as np

rng = np.random.default_rng() # create a random number generator

print(rng.integers(1, 7)) # generates a random integer between 1 and 6 (7 is exclusive) for a dice roll

print(rng.integers(low=1, high= 101)) # generates a random integer between 1 and 100 (101 is exclusive)

print(rng.integers(low=1, high= 101, size= 3)) # generates an array of 4 random integers between 1 and 100 (101 is exclusive)

print(rng.integers(low=1, high= 101, size= (3, 4))) # generates a 3x4 array of random integers between 1 and 100 (101 is exclusive)

3
6
[94 72 91]
[[57 67 80 96]
 [50 65 30 47]
 [70 65 31 40]]


In [ ]:
import numpy as np

rng = np.random.default_rng(seed = 1) #create a random number generator with a seed value of 1 for reproducibility

print(rng.integers(low=1, high= 101, size= (3, 2))) 


[[48 52]
 [76 96]
 [ 4 15]]


In [ ]:
import numpy as np

print(np.random.uniform())
 # run this code multiple times and you will get different random numbers between 0 and 1 each time.

0.8015905873978173


In [ ]:
import numpy as np

print(np.random.uniform(low = -1, high=1, size = 3))

# this will generate an array of 3 random numbers between -1 and 1 (1 is exclusive)

[ 0.91525912 -0.5333765   0.35405791]


In [ ]:
# shuffling an array

rng = np.random.default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

# this will shuffle the elements of the array in place, meaning that the original array will be modified and the order of the elements will be changed randomly each time you run the code.

[5 2 3 4 1]


In [53]:
rng = np.random.default_rng()
array = np.array(["apple", "banana", "cherry", "date", "elderberry"])
fruit = rng.choice(array) # randomly selects an element from the array
fruits = rng.choice(array, size=(3, 2)) # randomly selects 6 elements from the array and arranges them in a 3x2 array print(fruit) print(fruits)

rng.shuffle(array)
print(array)

['elderberry' 'apple' 'cherry' 'date' 'banana']
